services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - "127.0.0.1:8090:8090"
    volumes:
      - beszel-data:/beszel_data
      - beszel-socket:/beszel_socket

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - beszel-socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "/mnt/main:/extra-filesystems/main Volume:ro"
      - "/mnt/storagebox:/extra-filesystems/Storagebox:ro"
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: "${BESZEL_KEY}"

volumes:
  beszel-data:
  beszel-socket:
